Importing basic libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Getting data

In [4]:
# Feature extracted vector of butterfly images
df = pd.read_csv("datasets/final_dataset.csv")

# showing top fifth
df.head()

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,target
0,29.275214,-0.147201,-1.335186,5.263774,2.933685,-14.615108,7.565177,-8.898978,-16.116767,7.206693,...,3.754211,1.955780,-2.846820,-2.594667,-1.665765,11.178280,-7.645203,4.779743,0.896216,1
1,43.960923,-25.890576,22.524388,-3.134579,32.609728,-19.598023,17.939081,18.361859,-21.754190,-17.046747,...,-0.120588,-3.840173,8.638707,3.882905,-5.455157,-0.468976,-11.277624,-0.663129,-0.497319,1
2,5.218205,3.084408,-27.803279,-2.221283,-5.707876,-8.569674,0.951585,5.912482,5.848390,10.257646,...,-10.112489,-3.959618,13.063066,54.582594,-12.624812,1.808988,-4.303192,17.549340,8.711923,1
3,-20.494164,-18.120083,-15.401201,2.056117,18.834858,16.911382,0.487602,10.095791,8.490112,0.917253,...,-9.844180,3.275873,-4.053599,-6.252846,-7.054679,10.603682,-0.834759,4.843701,-1.522923,1
4,3.769366,-26.453038,-16.908507,12.519255,2.701589,-1.982461,21.484898,15.607886,14.941911,-12.432393,...,6.485967,-3.365990,6.606531,-3.953705,5.060607,23.305445,-2.619473,-7.971622,-25.330169,1

Splitting dataframe

In [36]:
from sklearn.model_selection import StratifiedShuffleSplit

X = df.drop(columns = 'target').copy().to_numpy()
y = df.target.copy().to_numpy()

sss = StratifiedShuffleSplit(n_splits = 1, test_size = 0.15, random_state = 10)

for trainval_index, test_index in sss.split(X, y):
    X_trainval, X_test = X[trainval_index], X[test_index]
    y_trainval, y_test = y[trainval_index], y[test_index]
    
for train_index, val_index in sss.split(X_trainval, y_trainval):
    X_train, X_val = X_trainval[train_index], X_trainval[val_index]
    y_train, y_val = y_trainval[train_index], y_trainval[val_index]

In [ ]:
from sklearn_custom.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
lr = OneVsRestClassifier(LogisticRegression())
lr.fit(X_train, y_train)